# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: pminsu01
email: Erjuer01@gmail.com
description: 개발과 여행 그리고 사람을 좋아하는 개발자 입니다.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://pminsu01.github.io" # the base hostname & protocol for your site
github_username:  pminsu01
github:
  repo: https://github.com/pminsu01
# Build settings
gems: [jekyll-paginate]

markdown: kramdown
kramdown:
    input: GFM
    hard_wrap: false

permalink: ":year-:title/"

# Collections
collections:
  works:
    output: true

# Pagination
paginate: 4
paginate_path: ":num/"


defaults:
    -
        scope:
            path: ""
            type: "posts"
        values:
            layout: "post"
    -
        scope:
            path: ""
            type: "pages"
        values:
            layout: "page"
